### ISSUE TITLE
scrollback module bug - racyness

### ISSUE THREAD

**Issue by euank** [euank/EuIrcBot#104]
You can end up in a race between viewing and adding an item to scrollback.

Ultimately, this can't be resolved correctly-for-all-cases IMO without adding a sequence number to all message/command events, and using that sequence number as a way to request scrollback prior to it.

An example of triggering this bug:

```
<ek> !quo "/this doesnt exist anywhere above/"
<bot> Cannot find line matching regex /this doesnt exist anywhere above/
<bot> https://twitter.com/xxxxxxx/xxxxx
```

The calls that are racing are `scrollback.getFormattedScrollbackLinesFromRanges` and `scrollback.chansay`. Racing isn't totally the correct word because it's actually deterministic (thanks event loops!) but it gets the point across well.
The first call to get scrollback works correctly, but issues a new message to the channel. This new message is added to scrollback prior to the second get scrollback call.

There might be other ways to fix this than sequence numbers (e.g. improving the way a command can hit multiple modules and gather output prior to acting in a way which hits scrollback), but I think a sequence number is the cleanest and best solution.

**Comment by euank** [comment]
@LinuxMercedes we fixed this, right?

**Comment by LinuxMercedes** [comment]
```
12:02:33      `lm` | !quo /dongles/
12:02:33          ^ | Cannot find line matching regex /dongles/; only have 999 lines of context 
12:02:33          ^ | https://twitter.com/QuothTheDong/status/774654305898901504
```
Nope :disappointed:
