### ISSUE TITLE
OnMath scrollback ordering problem?

### ISSUE THREAD

**Issue by LinuxMercedes** [euank/EuIrcBot#124]
The following commands in IRC:

```
<`lm`> 5*90
<^> 450 
<`lm`> !quo 2,1
```

produce the following quote:

```
<^> 450 
<`lm`> 5*90
```

which is not as it ought to be. 

--EDIT--
However, something similar:

```
<`lm`> !hb 
<^> HAPPY BIRTHDAY SHEPARD
<`lm`> !quo 2,1
```

produces output as expected:

```
<`lm`> !hb 
<^> HAPPY BIRTHDAY SHEPARD
```

---EDIT---

Perhaps there is an issue with how OnMath responses are placed into scrollback?

**Comment by brhoades** [comment]
I just glanced at onMath, as it's been a while, and it just uses reply for output like this. I'd 👉  at scrollback instead.

**Comment by LinuxMercedes** [comment]
Duplicate of #131
