### ISSUE TITLE
Url shorten module

### ISSUE THREAD

**Issue by euank** [euank/EuIrcBot#29]
Should allow you to shorten a url (e.g. !shorten url google.com), show what a given short url leads to (!unshorten url bit.ly/dong ... just follows redirects).... For each of those, there should be a corresponding !shorten last 1 (maybe seen 1) that shortens the last url said.

**Comment by Abdiramen** [comment]
If you're not using an API i'm not sure if the first half of this module can be done without first creating a database and a server for the shortenings.

**Comment by euank** [comment]
Oh wow, 4 year old issue. Back then I ran a public url shortening service (since moved to read-only), so I probably assumed it would use that.

I'm no longer sure how much value the shorten portion would provide. Unshorten could still be handy.
