### ISSUE TITLE
Add nickserv support

### ISSUE THREAD

**Issue by LinuxMercedes** [euank/EuIrcBot#76]
Allow Euircbot to have a regisered nick like a real person.

**Comment by euank** [comment]
:+1: 

I'm only slightly offended by your implicit dehumanization of those who choose to be mal-nickserved, whether due to societal or  other reasons.

**Comment by LinuxMercedes** [comment]
I only dehumanize those incapable of using nickserv, not those who simply choose not to. 

That being said, I understand that affect > intent, and for my words I sincerely apologize.
