### ISSUE TITLE
!quo support for /me

### ISSUE THREAD

**Issue by brhoades** [euank/EuIrcBot#78]
Currently if you !quo someone who used /me, it does something like this:
https://twitter.com/QuoteDeskEng/status/597849593355767808
Ideally we could have it go * someone did this * instead.

**Comment by LinuxMercedes** [comment]
https://twitter.com/QuothTheDong/status/585857826280448000

Maybe something is messed up with your config/marko's method of handling ACTIONs?

**Comment by brhoades** [comment]
That's possible, it could be due to a different network using different action formatting and marko / our clients use both. This appeared properly in chat but ^ didn't seem to think so.

**Comment by LinuxMercedes** [comment]
After having looked inside node-irc, it wouldn't surprise me at all if something was broken there.
