### ISSUE TITLE
Nickserv module is too async

### ISSUE THREAD

**Issue by LinuxMercedes** [euank/EuIrcBot#95]
It's possible for nickserv auth to not complete before the bot tries to join channels. I'm not sure why I didn't forsee this. 

I guess that means that part of nickserv needs to come out of a module and into the main bot itself.

**Comment by euank** [comment]
I don't think the order of channel joining vs nickserv identifying matters.

If the module `init` is called before the bot has connected to irc, then I'd say that's a bug and the bot should wait for 'welcome' before initing things.

If `nickserv` really needs to be after the `join` module, you could emit events from `join` that `nickserv` fires off of.

This is the sort of thing that would fit fine in the core bot, but I don't think it needs to be there.

**Comment by LinuxMercedes** [comment]
The order of channel joining and nickserv identifying matters if you want it in a channel with mode +R (i.e. only allow registered nicks). 

Module init is called after connecting but before joining; that part is right. 

The issue is this line, I think: https://github.com/euank/EuIrcBot/blob/master/modules/nickserv.js#L7

Maybe a better fix would be to force that to complete before nickserv's init returns?

**Comment by euank** [comment]
We should revisit this at some point.

The fix should probably be the nickserv module emitting an event ('logged-in' or 'authed' or such) and join using that event to re-try failed channels... just throwing that out there.

Making nickserv/auth a core part of the bot makes emitting such an event easier with how it's currently setup

**Comment by LinuxMercedes** [comment]
The 'chained event' type thing sounds pretty good. What happens if the bot tries to join a channel it's already in?

**Comment by euank** [comment]
afaik, nothing bad.
